"""changed nullable=False to nullable=True in order_item_id

Revision ID: 566c54e331d3
Revises: 7c3c84a27188
Create Date: 2025-12-29 12:25:47.044265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566c54e331d3'
down_revision: Union[str, Sequence[str], None] = '7c3c84a27188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_keys', 'order_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_keys', 'order_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
