"""Changed status from enum to String

Revision ID: 5b376ae7781f
Revises: 8881a30c3bc2
Create Date: 2025-12-23 09:27:28.237957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b376ae7781f'
down_revision: Union[str, Sequence[str], None] = '8881a30c3bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_keys', sa.Column('order_item_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'product_keys', ['key_value'])
    op.drop_column('product_keys', 'orders_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_keys', sa.Column('orders_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_keys', type_='unique')
    op.drop_column('product_keys', 'order_item_id')
    # ### end Alembic commands ###
