"""add nullable=False for order_item_id

Revision ID: 7c3c84a27188
Revises: 5b376ae7781f
Create Date: 2025-12-23 09:32:02.214094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3c84a27188'
down_revision: Union[str, Sequence[str], None] = '5b376ae7781f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_keys', 'order_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_keys', 'order_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
